name: Release

on:
  release:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}::node:${{ matrix.node }} build - lint - test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ 16.x ]
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: use node version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        uses: bahmutov/npm-install@v1

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: generate api
        run: yarn generate:api

      - name: test
        run: yarn cover

  publish-gpr:
    name: publish package on github registry
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16.x ]
        os: [ ubuntu-latest ]

    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: use node version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'

      - name: install dependencies
        run: yarn install

      - name: publish
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
